In jar_jar rule, enable setting jvm_flags
bazeltools/bazel_jar_jar pull request #55
Opened 2024-10-29 18:43 UTC by thomasbao12

2024-10-29 19:30 UTC, thomasbao12 commented
I honestly could use some guidance around how to better test this

2024-11-01 19:25 UTC, thomasbao12 commented
Friendly poke: @johnynek @eed3si9n

2024-11-01 20:04 UTC, fmeum commented on internal/jar_jar.bzl
> +        args.add("--jvm_flags={}".format(" ".join(ctx.attr.jvm_flags)))
`args.add_joined` would be more memory efficient, but it won't matter much since there typically aren't that many targets for this rule.

2024-11-01 22:58 UTC, thomasbao12 commented on internal/jar_jar.bzl
> +        args.add("--jvm_flags={}".format(" ".join(ctx.attr.jvm_flags)))
args.add_joined inserts a space between the argument name and values, so am going to merge as is.

1. I tried the following change:
```
-        args.add("--jvm_flags={}".format(" ".join(ctx.attr.jvm_flags)))
+        args.add_joined("--jvm_flags=", ctx.attr.jvm_flags, join_with=" ")
```
2. bazel aquery output
```
  Command Line: (exec bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/external/bazel_jar_jar~/src/main/java/com/github/johnynek/jarjar/app \
    '--jvm_flags=' \
    '-Xmx2g -Xloggc:/tmp/gc.log' \
```

2024-11-01 23:00 UTC, thomasbao12 commented
@fmeum Would you be able to merge this PR?

2024-11-01 23:17 UTC, eed3si9n commented on test/jar_jar/example/BUILD
> +        "-Xloggc:/tmp/gc.log",
Maybe this fails on Windows?

```
ERROR: D:/a/bazel_jar_jar/bazel_jar_jar/test/jar_jar/example/BUILD:23:8: jarjar @@//jar_jar/example:shaded_args failed: (Exit 1): app.exe failed: error executing Action command (from target //jar_jar/example:shaded_args) bazel-out\x64_windows-opt-exec-ST-d57f47055a04\bin\external\bazel_jar_jar~\src\main\java\com\github\johnynek\jarjar\app.exe --jvm_flags=-Xmx2g -Xloggc:/tmp/gc.log process jar_jar/example/shade_rule ... (remaining 2 arguments skipped)
```

2024-11-01 23:18 UTC, eed3si9n requested changes
CI is failing on Windows.

2024-11-02 07:50 UTC, fmeum commented on internal/jar_jar.bzl
> +        args.add("--jvm_flags={}".format(" ".join(ctx.attr.jvm_flags)))
Feel free to merge as is, but this should work:
```
args.add_joined(ctx.attr.jvm_flags, join_with=" ", format_joined="--jvm_flags=%s")
```

2024-11-05 16:55 UTC, eed3si9n approved these changes

2024-11-05 16:56 UTC, merged